In [1]:
import numpy as np
from IPython.display import display

In [4]:
#1
num_a= np.arange(1, 16+1)
print(num_a)
num_a.reshape(4, 4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
#2
num_b= np.arange(10, 50 , 5)
print(num_b)
num_b.reshape(2 , 4)

[10 15 20 25 30 35 40 45]


array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [11]:
#3
np.random.seed(3)
rand_array = np.random.randint(0, 101, (3, 3))
print(rand_array)
print('max', rand_array.max()) 
print('min', rand_array.min()) 

[[24  3 56]
 [72  0 21]
 [19 74 41]]
max 74
min 0


In [16]:
#4
arr_d = np.arange(10,20+1)
print('arr_d[:5]',arr_d[:5])
print('arr_d[:5]',arr_d[::2])
print('arr_d[:5]',arr_d[::-1])

arr_d[:5] [10 11 12 13 14]
arr_d[:5] [10 12 14 16 18 20]
arr_d[:5] [20 19 18 17 16 15 14 13 12 11 10]


In [22]:
#5
arr = np.random.randint(1, 50+1, (4, 5))
print(arr)
print('second row',arr[1])
print('last row',arr[-1])

[[17 35 40  2 36]
 [46  2 19  3 24]
 [36 21 18 23 29]
 [44  8 34 44 33]]
second row [46  2 19  3 24]
last row [44  8 34 44 33]


In [34]:
#6
np.random.seed(6)
arr = np.random.randint(0, 101, 15)
max_ind = np.argmax(arr)
min_ind = np.argmin(arr)
print(max_ind)
print(min_ind)

2
8


In [39]:
np.savetxt('array.txt', arr, fmt='%d')
#- מתוך המערך של ה- 15 איברים , צור מערך המכיל רק את האיברים המתחלקים ב - 5
arr_5 = arr[arr % 5 == 0]
print(arr_5)
#- צור והדפס מערך המכיל את כל המספרים הגדולים מ- 50 או קטנים מ- 10 )מתוך ה - 15(
arr_10_50 = arr[(arr > 50) | (arr < 10)]
print(arr_10_50)

[10 80 25 75]
[73 99 84 79 80 62  1 75 77 57 68]
